from django import template

register = template.Library()

@register.filter(name = 'humanize_model')
def humanize_model(s):
    human_names = {
        'pcode_abs-original' : 'human-composed clip',
        'pcode_abs-random' : 'randomly generated clip',
        'pcode_abs-gpt2' : 'clip generated by GPT-2 (pcode)',
        'dcode-gpt2' : 'clip generated by GPT-2 (dcode)',
        'pcode_abs-lstm' : 'clip generated by an LSTM (pcode)'
    }
    return human_names[s]
