from django import template

register = template.Library()

@register.filter(name = 'humanize_model')
def humanize_model(s):
    human_names = {
        'pcode_abs-original' : 'composed by a human',
        'pcode_abs-gpt2' : 'generated by GPT-2 (pcode)',
        'pcode_abs-lstm' : 'generated by an LSTM (pcode)'
    }
    return human_names[s]

@register.filter(name = 'mp3path')
def mp3path(s):
    return 'static-clips/%s.mp3' % s
