from django import template
from django.conf import settings as settings

register = template.Library()

@register.filter(name = 'humanize_model')
def humanize_model(s):
    human_names = {
        'pcode_abs-original' : 'human-composed clip',
        'pcode_abs-random' : 'randomly generated clip',
        'pcode_abs-gpt2' : 'clip generated by GPT-2 (pcode)',
        'dcode-gpt2' : 'clip generated by GPT-2 (dcode)',
        'pcode_abs-lstm' : 'clip generated by an LSTM (pcode)'
    }
    return human_names[s]

@register.filter(name = 'clips_static_url')
def clips_static_url(clip):
    fmt = '%smusicsurvey/%s.%s'
    return fmt % (settings.STATIC_URL, clip.name,
                  settings.MUSICSURVEY_FILE_TYPE)
